### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by reidjr2**
Hardcode 1342 as PIN code. Easylife Go will work. This is a Hack, change PIN code to match default 1234, or of course your own !

### CODE REVIEW

**Comment by reidjr2** [comment]
Hi Andy, fantastic work. Updating the config_flow has defeated me, but adding this simple addition ( with perhaps the default pin code ? ) gives a hard coded Pin that works.

**Comment by andyb2000** [comment]
Thanks for this, looks really promising, I'm going to not merge this PR as want to implement this without hacking code at this point. I'm working on PIN entry to do this via config_flow but I'm away at the moment so cannot test and merge fully.

**Comment by reidjr2** [comment]
When you think you are a point to test, happy to do that here.

**Comment by lasry1** [comment]
i can confirm adding the code in that line works, i can now fully control the mower. Thank you!

**Comment by andyb2000** [comment]
I'm going to close this one off since starting to implement pin via config_flow in #dev7

**Pull request closed without merging**
